scan_filter_chain:
- name: AngularBoundFilter
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    # filtering 1 : angle 
    lower_angle: -3.14
    upper_angle: 0

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    # filtering 2 : distance / range
    filter_type: 1
    max_range: 0.1
    max_range_difference: 0.1
    filter_window: 2